version: '3.8'

services:
  mosquitto-broker:
    image: eclipse-mosquitto:2.0.22
    container_name: mosquitto-broker
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  pi3-subscriber:
    build:
      context: .
      dockerfile: Dockerfile.subscriber
    container_name: pi3-subscriber
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - /dev:/dev
      - /proc:/proc
      - ./subscriber.py:/app/subscriber.py
      - ./iot_hub_client.py:/app/iot_hub_client.py
    depends_on:
      - mosquitto-broker
    environment:
      - BROKER_HOST=10.244.134.153
      - BROKER_PORT=1883
      - TOPIC=deepstream/car_count
      - GPIOZERO_PIN_FACTORY=lgpio
      - IOT_HUB_CONNECTION_STRING=${IOT_HUB_CONNECTION_STRING}
   
  webpanel:
    build: ./webpanel
    container_name: webpanel
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - mosquitto-broker
    env_file:
      - ./.env

  telegram-bot:
    build: ./telegram_bot
    container_name: telegram-bot
    restart: unless-stopped
    depends_on:
      - mosquitto-broker
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_PORT=${MQTT_PORT:-1883}
    volumes:
      - ./telegram_bot/data:/app/data
